# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8bb20405807cd1a2b1dc54ffbe1aa3a084241f391faa637f3c8f303e8fc2ccac9815a487b9df194bbcdc79675e961028c3651f3335b2091202c42eff97267cc0

test:
  secret_key_base: 83a4f73bf9fd102b97c8bd39710995b87f6f2ba13dc09d4a41d29defed324d8f7de94a34118f47015fc002794f42e75d21b205b103f9f5996a20b1a8463e7d50

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
